#cloud-config

package_update: true
package_upgrade: false

ssh_pwauth: false

packages:
  - ncurses-bin

write_files:
  - path: /etc/ssh/sshd_config.d/99-hardening.conf
    owner: root:root
    permissions: "0644"
    content: |
      KbdInteractiveAuthentication no

runcmd:
  - sshd -t
  - systemctl reload ssh || systemctl reload sshd
  - curl -fsSL https://tailscale.com/install.sh | sh
  - tailscale up --auth-key='${tailscale_auth_key}' --hostname='${hostname}'